name: Deploy OpenMBEE to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up SSH Key
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Install Dependencies
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.208.197.217 "
          sudo yum install -y libxcrypt-compat
        "

    - name: Install Docker and Docker Compose if Not Present
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.208.197.217 "
          if ! command -v docker &> /dev/null; then
            sudo amazon-linux-extras install docker -y
            sudo systemctl enable docker
            sudo systemctl start docker
          fi

          if ! command -v docker-compose &> /dev/null; then
            sudo curl -L 'https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)' -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
          fi
        "

    - name: Create Directory and Set Permissions
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.208.197.217 "
          sudo mkdir -p /opt/openmbee
          sudo chown ec2-user:ec2-user /opt/openmbee
        "

    - name: Copy Docker Compose File
      run: |
        scp docker-compose.yml ec2-user@54.208.197.217:/opt/openmbee

    - name: Deploy OpenMBEE
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.208.197.217 "cd /opt/openmbee && docker-compose up -d"