name: Deploy OpenMBEE to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up SSH Key
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Remove Existing Directory and Clone Repository to Server
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.208.197.217 "
          sudo rm -rf /opt/openmbee
          sudo git clone https://github.com/avianinc/OpenMBEE.git /opt/openmbee
          sudo chown -R ec2-user:ec2-user /opt/openmbee
        "

    - name: Install Docker and Docker Compose if Not Present
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.208.197.217 "
          if ! command -v docker &> /dev/null; then
            sudo yum install docker -y
            sudo systemctl enable docker
            sudo systemctl start docker
          fi
        "

    - name: Deploy OpenMBEE
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.208.197.217 "sudo cd /opt/openmbee && docker-compose up -d"
